# Generated by Django 5.1.2 on 2024-10-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_model',
            new_name='food',
        ),
    ]
