# Generated by Django 5.1.2 on 2024-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_food_model_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
